---
title: ""
output: html_document
date: '2022-06-01'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

## Microclimatic point estimates


#### Data
```{r}
#library(climate)
library(hydroTSM)
library(tidyverse)
library(lubridate)
data <- read_csv("data/data.csv") %>%
  mutate(cd = mdy(date)) %>% 
  mutate(yd = yday(cd))

mz <- data %>% 
  filter(researcher == "mz")

ng <- data %>% 
  filter(researcher == "ng")

data_augment <- data %>% 
  filter(microsite != c("high"))

```


#### Viz
```{r}
#all data
ggplot(data) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

ggplot(data) +
  geom_line(aes(yd, humidity, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

#density only
ggplot(mz) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

ggplot(mz) +
  geom_line(aes(yd, humidity, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

#shelter-expt
ggplot(ng) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

ggplot(ng) +
  geom_line(aes(yd, humidity, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1")

ggplot(ng) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  facet_wrap(~site) +
  scale_color_brewer(palette = "Set1")

ggplot(ng) +
  geom_line(aes(yd, humidity, color = microsite), size = 2) +
  facet_wrap(~site) +
  scale_color_brewer(palette = "Set1")


#climograph just shelter
ggplot(ng) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  geom_point(aes(yd, humidity, color = microsite), size = 1) +
  scale_color_brewer(palette = "Set1") +
  scale_y_continuous(name = 'temp',
                     sec.axis = sec_axis(~., name = 'humidity')) +
  facet_wrap(~site)


#shelters + open
ggplot(data_augment) +
  geom_line(aes(yd, temperature, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(~site)

ggplot(data_augment) +
  geom_line(aes(yd, humidity, color = microsite), size = 2) +
  scale_color_brewer(palette = "Set1") +
  facet_wrap(~site)

```

